name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - scipath/**/*.py
      - tests/**/*.py
      - benchmarks/**/*.py

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-python.yml@main
    with:
      recursive-clone: true
