name: Test

on:
  push:
    paths:
      - .github/workflows/main.yml
      - pyproject.toml
      - uv.lock
      - scipath/**
      - tests/**

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12, 3.13, 3.14]
        runs-on: [ubuntu, windows, macos]

    uses: winstxnhdw/actions/.github/workflows/uv.yml@main
    with:
      runs-on: ${{ matrix.runs-on }}-latest
      recursive-clone: true
      python-version: ${{ matrix.python-version }}
      install-project: true
